### ISSUE TITLE
Regex to search auto-reply module not sanitized/escaped

### ISSUE THREAD

**Issue by RaenonX** [RxJellyBot/Jelly-Bot#323]
## Description
As title.

## Expected Behavior
Sanitize/escape the input so that if there's any incomplete parentheses, the search could still be performed.

## Current Status
Not fixed.

## How to reproduce
Enter bot command `JC AR I (123）`

The right parentheses here is **NOT** paired with the left parentheses.

## Origin
N/A

## Notes
```
Traceback:
Traceback (most recent call last):
  File ".\msghandle\handle.py", line 44, in handle_message_main
    ret = HandledMessageEventsHolder(e.channel_model, fn_box[event_type](e))
  File ".\msghandle\text\main.py", line 30, in handle_text_event
    resp = fn(e)
  File ".\msghandle\text\botcmd.py", line 8, in process_bot_cmd
    return handle_bot_cmd_main(e)
  File ".\msghandle\botcmd\main.py", line 13, in handle_bot_cmd_main
    return cmd_handler.handle(e)
  File ".\msghandle\botcmd\command\_base.py", line 545, in handle
    return self._root.parse_args(e, command, splitter)
  File ".\msghandle\botcmd\command\_base.py", line 491, in parse_args
    return cmd_node.parse_args(e, command, splitter, cmd_node.max_arg_count, args=cmd_args, is_sub=True)
  File ".\msghandle\botcmd\command\_base.py", line 491, in parse_args
    return cmd_node.parse_args(e, command, splitter, cmd_node.max_arg_count, args=cmd_args, is_sub=True)
  File ".\msghandle\botcmd\command\_base.py", line 484, in parse_args
    return self._handle_fn(e, cmd_fn, args)
  File ".\msghandle\botcmd\command\_base.py", line 453, in _handle_fn
    ret = arg_type_ensure(fn=cmd_fn.fn, converter=NonSafeDataTypeConverter)(e, *args)
  File ".\extutils\checker\arg.py", line 173, in wrapper_in
    return _type_ensure(fn, converter, *args_cast, **kwargs_cast)
  File ".\extutils\checker\arg.py", line 218, in _type_ensure
    return fn(*new_args, **new_kwargs)
  File ".\msghandle\botcmd\command\ar.py", line 263, in auto_reply_module_detail
    conn_list = AutoReplyManager.get_conn_list(e.channel_oid, keyword)
  File ".\mongodb\factory\ar_conn.py", line 469, in get_conn_list
    return self._mod.get_conn_list(channel_oid, keyword, active_only)
  File ".\mongodb\factory\ar_conn.py", line 256, in get_conn_list
    return self.find_cursor_with_count(
  File ".\mongodb\factory\mixin\ctrlext.py", line 182, in find_cursor_with_count
    self.find(filter_, *args, **kwargs), self.count_documents(filter_), parse_cls=parse_cls)
  File "C:\Users\Administrator\Documents\Applications\Jelly-Bot\venv\lib\site-packages\pymongo\collection.py", line 1720, in count_documents
    return self.__database.client._retryable_read(
  File "C:\Users\Administrator\Documents\Applications\Jelly-Bot\venv\lib\site-packages\pymongo\mongo_client.py", line 1464, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "C:\Users\Administrator\Documents\Applications\Jelly-Bot\venv\lib\site-packages\pymongo\collection.py", line 1714, in _cmd
    result = self._aggregate_one_result(
  File "C:\Users\Administrator\Documents\Applications\Jelly-Bot\venv\lib\site-packages\pymongo\collection.py", line 1605, in _aggregate_one_result
    result = self._command(
  File "C:\Users\Administrator\Documents\Applications\Jelly-Bot\venv\lib\site-packages\pymongo\collection.py", line 235, in _command
    return sock_info.command(
  File "C:\Users\Administrator\Documents\Applications\Jelly-Bot\venv\lib\site-packages\pymongo\pool.py", line 603, in command
    return command(self.sock, dbname, spec, slave_ok,
  File "C:\Users\Administrator\Documents\Applications\Jelly-Bot\venv\lib\site-packages\pymongo\network.py", line 165, in command
    helpers._check_command_response(
  File "C:\Users\Administrator\Documents\Applications\Jelly-Bot\venv\lib\site-packages\pymongo\helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Regular expression is invalid: missing )
```

## Solution
Not yet resolved. Fixing commit to be mentioned after this had been fixed.

**Comment by RaenonX** [comment]
http://jira.raenonx.cc/browse/JB-87
